"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _sign_in from './sign-in.bones.json'
import _count from './count.bones.json'

registerBones({
  "sign-in": _sign_in,
  "count": _count,
})
